// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTaYCmd3adbK_hmEBrKvgUpGkdKpH6CMw',
    appId: '1:289080553746:web:a394ad99ace0ca9a4c43cb',
    messagingSenderId: '289080553746',
    projectId: 'punto-de-venta-moviles',
    authDomain: 'punto-de-venta-moviles.firebaseapp.com',
    storageBucket: 'punto-de-venta-moviles.firebasestorage.app',
    measurementId: 'G-FBG4ZCX96V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCufjrfirOXJsP43FFWQSwHjLZPTdR73_k',
    appId: '1:289080553746:android:3adf573d6328ff764c43cb',
    messagingSenderId: '289080553746',
    projectId: 'punto-de-venta-moviles',
    storageBucket: 'punto-de-venta-moviles.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkTiydNYTffSRG9vKMMOAmaEpzQYnw1mY',
    appId: '1:289080553746:ios:e87ba4cae6820d494c43cb',
    messagingSenderId: '289080553746',
    projectId: 'punto-de-venta-moviles',
    storageBucket: 'punto-de-venta-moviles.firebasestorage.app',
    iosBundleId: 'com.example.puntoDeVenta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkTiydNYTffSRG9vKMMOAmaEpzQYnw1mY',
    appId: '1:289080553746:ios:e87ba4cae6820d494c43cb',
    messagingSenderId: '289080553746',
    projectId: 'punto-de-venta-moviles',
    storageBucket: 'punto-de-venta-moviles.firebasestorage.app',
    iosBundleId: 'com.example.puntoDeVenta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTaYCmd3adbK_hmEBrKvgUpGkdKpH6CMw',
    appId: '1:289080553746:web:3220427b39b7cc064c43cb',
    messagingSenderId: '289080553746',
    projectId: 'punto-de-venta-moviles',
    authDomain: 'punto-de-venta-moviles.firebaseapp.com',
    storageBucket: 'punto-de-venta-moviles.firebasestorage.app',
    measurementId: 'G-ME6GBKY33S',
  );
}
